"""Initial tables

Revision ID: 5c0d741c07e3
Revises: 
Create Date: 2025-04-08 20:16:39.480840

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5c0d741c07e3'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('creative_competitions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('max_score', sa.Integer(), nullable=True),
    sa.Column('criteria_ids', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_creative_competitions_id'), 'creative_competitions', ['id'], unique=False)
    op.create_index(op.f('ix_creative_competitions_name'), 'creative_competitions', ['name'], unique=True)
    op.create_table('criteria',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_criteria_id'), 'criteria', ['id'], unique=False)
    op.create_index(op.f('ix_criteria_name'), 'criteria', ['name'], unique=True)
    op.create_table('sport_competitions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('max_score', sa.Integer(), nullable=True),
    sa.Column('criteria_ids', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sport_competitions_id'), 'sport_competitions', ['id'], unique=False)
    op.create_index(op.f('ix_sport_competitions_name'), 'sport_competitions', ['name'], unique=True)
    op.create_table('teams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_teams_id'), 'teams', ['id'], unique=False)
    op.create_index(op.f('ix_teams_name'), 'teams', ['name'], unique=True)
    op.create_table('penalties',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=300), nullable=True),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_penalties_id'), 'penalties', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_penalties_id'), table_name='penalties')
    op.drop_table('penalties')
    op.drop_index(op.f('ix_teams_name'), table_name='teams')
    op.drop_index(op.f('ix_teams_id'), table_name='teams')
    op.drop_table('teams')
    op.drop_index(op.f('ix_sport_competitions_name'), table_name='sport_competitions')
    op.drop_index(op.f('ix_sport_competitions_id'), table_name='sport_competitions')
    op.drop_table('sport_competitions')
    op.drop_index(op.f('ix_criteria_name'), table_name='criteria')
    op.drop_index(op.f('ix_criteria_id'), table_name='criteria')
    op.drop_table('criteria')
    op.drop_index(op.f('ix_creative_competitions_name'), table_name='creative_competitions')
    op.drop_index(op.f('ix_creative_competitions_id'), table_name='creative_competitions')
    op.drop_table('creative_competitions')
    # ### end Alembic commands ###
